# Generated by Django 4.2 on 2025-01-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vetweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
