# Generated by Django 4.2 on 2025-01-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetweb', '0004_producto_pdf_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdfs'),
        ),
    ]
