# Generated by Django 4.2 on 2025-01-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetweb', '0005_alter_producto_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
