# Generated by Django 4.2 on 2025-01-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetweb', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], max_length=10),
        ),
    ]
