# Generated by Django 4.2 on 2025-01-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetweb', '0008_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10),
        ),
    ]
