# Generated by Django 4.2 on 2025-02-01 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetweb', '0011_listadeseos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='es_estatico',
            field=models.BooleanField(default=False),
        ),
    ]
